config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products
  root 'products#index'

  resources :categories do
    resources :product_groups
  end

  post '/cart' => 'cart#add_to_cart'
  get '/cart' => 'cart#index'
  patch '/cart' => 'cart#update_cart'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :product_groups, dependent: :destroy
  has_many :products, through: :product_groups
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  monetize :price_cents

  before_validation :set_price

  private

  def set_price
    self.price = product.price * quantity
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :products, through: :line_items
  monetize :total_price_cents
  accepts_nested_attributes_for :line_items

  def refresh_total
    self.total_price_cents = line_items.map{|line_item| line_item.price_cents}.reduce(:+)
    save
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :product_group
  has_many :line_items
  has_many :orders, through: :line_items
  monetize :price_cents
end

app/models/product_group.rb
# frozen_string_literal: true

class ProductGroup < ApplicationRecord
  has_many :products, dependent: :destroy
  belongs_to :category
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cart_controller.rb
# frozen_string_literal: true
class CartController < ApplicationController
  def index
    @products = []
    cart = session[:cart] 
    cart.keys.each{|key| @products << Product.find(key.to_i)} if cart
    @total = @products.map{|product| product.price_cents * session[:cart][product.id.to_s]}.reduce(:+)
  end

  def add_to_cart
    cart = CartService.new(session[:cart])
    cart.add(params[:product], params[:quantity])
    session[:cart] = cart.data
    redirect_back fallback_location: root_path
  end

  def update_cart
    checked = params[:checked_product_ids]
    product_ids = params[:product_ids]
    product_quantities = params[:product_quantities]
    #check if any products are checked for removal from cart
    if checked
      checked.each_with_index do |id, index| 
        session[:cart].delete(id)
        # delete the ids and quantities from params since we don't want do edit them after
        # deleting them 
        product_ids.delete_at(index)
        product_quantities.delete_at(index)
      end
    end
    #now we can edit whatever we are left with
    product_ids.each_with_index do |id, index|
      session[:cart][id] = product_quantities[index].to_i
    end
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @product_groups = @category.product_groups
    @products = @category.products
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
	def create
		order = current_user.orders.new
		session[:cart].each do |product_id, quantity|
			# find the product the the line_item belongs to. we need it to set the price of the
			# line_item as well
			product = Product.find(product_id.to_i)
			order.line_items << LineItem.create(quantity: quantity, product: product)
		end
		#this instance method also saves the order
		order.refresh_total
		session[:cart] = nil
		redirect_to root_path
	end
end

app/controllers/product_groups_controller.rb
# frozen_string_literal: true

class ProductGroupsController < ApplicationController
  def show
    @category = Category.find(params[:category_id])
    @product_groups = @category.product_groups
    @product_group = @product_groups.find(params[:id])
    @products = @product_group.products
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @category = Category.first
    @product_groups = @category.product_groups
    @products = @category.products
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # def list_categories
  #   categories = Category.all
  #   categories.each do |category|
  #     link_to category.name, category, class: "nav-item nav-link"
  #   end
  # end

  def product_group_breadcrumb_li(product_group)
    if product_group
      content_tag(:li, product_group.name, class: 'breadcrumb-item active', "aria-current": 'page')
    else
      content_tag(:li, 'All PRODUCTS', class: 'breadcrumb-item active', "aria-current": 'page')
    end
  end

  def total_items_in_cart
    if session[:cart]
      session[:cart].map{|k, v| v}.reduce(:+)
    end
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/product_groups_helper.rb
# frozen_string_literal: true

module ProductGroupsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/cart/index.html.erb
<h1>Cart</h1>


<div class="shopping-cart">

  <%= form_tag cart_path, method: :patch do %>

    <table class="table">

      <thead>
        <tr>
          <th id="header-remove">Remove</th>
          <th id="header-img">Image</th>
          <th>Product(s)</th>
          <th>Price</th>
          <th>Qty</th>
          <th id="header-total">TOTAL</th>
        </tr>
      </thead>

      <tbody>

        <% @products.each do |product| %> 

          <%= hidden_field_tag "product_ids[]", product.id %>
          <tr>
            <td id="td-checkbox">
              <%= check_box_tag "checked_product_ids[]", product.id %>
            </td>

            <td id="td-img">
              <div class="image"></div>
            </td>

            <td id="product-name">
              <label>
                 <%= product.description %>
              </label>
            </td>

            <td id="td-price">
              <span class="price"><%= product.price_cents %></span> AED
            </td>

            <td id="td-qty">
            
              <%= number_field_tag "product_quantities[]", session[:cart][product.id.to_s], class: "qty-inp" %>
            </td>
            <td id="td-total">
              <div class="div-total">
                <span class="total-val"><%= product.price_cents * session[:cart][product.id.to_s] %></span><span> AED</span>
              </div>
            </td>
          </tr>
        <% end %>

        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td id="td-sum-total">
            TOTAL OF:
          </td>
          <td id="td-sum-total-val">
            <div class="div-total">
              <span id="sum-total-val"><%= @total %></span> <span>AED</span>
            </div>
          </td>
        </tr>

      </tbody>
    </table>
    <div class="buttons">
      <%= submit_tag "Update Shopping Cart", class: "btn btn-secondary" %>
    </div>
  <% end %>
  <%= button_to "Create Order", orders_path, class:"btn btn-primary float-right" %>
</div>

app/views/categories/show.html.erb
<%= render 'products/list' %>

app/views/product_groups/show.html.erb
<%= render 'products/list' %>

app/views/products/_list.html.erb
<%= content_for :before do %>
  <%= render "products/nav" %>
  <div class="container mt-5">
    <div class="row">
      <div class="col-sm-12">
        <nav aria-label="breadcrumb ml-2">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to @category.name, @category %></li>
            <!-- custom view helper in products_helper.rb to vew the product view breadcrumb -->
            <%= product_group_breadcrumb_li(@product_group) %> 
          </ol>
        </nav>
      </div>
    </div>
  </div>
</nav>
<% end %>

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-3">
        <div class="card mt-5">
          <!-- <img src="" class="card-img-top" alt="..."> -->
          <!-- Div below is placeholder for image. Remove once we get real images -->
          <div style="width: 100%; height: 200px; background: #ccc" class="card-img-top"></div>
          <div class="card-body">
            <h6 class="card-title"><%= product.description %></h6>
            <p class="cart-text">
              <strong>AED <%= product.price_cents %></strong>
            </p>

            <div class="input-group">
              <div class="input-group-append">
                <%= form_tag cart_path(product: product.id) do %>
                  <%= number_field_tag :quantity, 1, within: 1..1000, class: 'form-control' %>
                  <%= button_tag :submit, class: "btn btn-primary" do %>
                    <i class="fa fa-cart-plus text-light"></i>
                  <% end %>
                <% end %>
              </div>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- <input type="number" class="form-control" value="1" min="1" max="1000">
              <div class="input-group-append">
                <button class="btn btn-primary">
                  <i class="fa fa-cart-plus text-light"></i>
                </button>
              </div> -->

app/views/products/_nav.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3">
      <h4 class="text-center">Categories</h4>
      <nav class="nav nav-pills flex-column pl-4">
        
        <% Category.all.each do |category| %>
          <% active_class = category == @category ? "active" : "" %>
          <%= link_to category.name, category, class: "nav-item nav-link #{active_class}" %>
        <% end %>

      </nav>
    </div>

    <div class="col-9">
      <h4>Product Groups</h4>
      <!-- The idea here is to use text-primary class for selected group and text-secondary for all others" -->
      <% @product_groups.each do |pg| %>
        <!-- check if @product_category varialble exists(we are in product_group show page)-->
        <% text_class = @product_group && pg == @product_group ? "text-primary" :  "text-secondary" %>
        <%= link_to pg.name, category_product_group_path(pg.category, pg), class: text_class %>
        <br />
      <% end %>
      
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= render 'list' %>